import { state, save, totalActivityHours, STATE_KEY } from './store.js';
import { localDateKey, formatHours } from './util.js';
import { applyBackstory } from './backstory.js';

// Screenshot fixture. Nothing here runs unless the page is opened with ?demo
// or the profile already carries a demoMode flag — it exists so the Home tab
// can be photographed with a year of believable history instead of three
// months of one. Once switched on it stays on across refreshes, and
// re-generates itself on a later day so the streak always ends today.
//
// The history itself is generated by backstory.js, the same module that writes
// the lasting three-month history a new profile starts with; only the window,
// the goals and the park-and-restore behaviour differ.

// The real profile is parked here while demo mode is on, so `?demo=clear` can
// hand back whatever walks the user had actually logged.
const PRE_DEMO_KEY = 'photowalk:pre-demo-state';

const DEFAULTS = {
  seed: 20260908,
  days: 364, // one full heatmap year, ending today
  streakDays: 9, // consecutive days ending today — must cover the current week
  weekFill: 0.72, // how full the weekly goal bar should read in the shot
  weeklyGoal: 3,
  // Sized so Month and Year also read as progress-in-flight if the segment is
  // tapped during a demo, instead of one bar full and another empty.
  monthlyGoal: 15,
  yearlyGoal: 200,
  // The odds of going out on a given day, climbing across the year as the habit
  // takes hold.
  baseChance: 0.16,
  rampChance: 0.34,
  weekendBonus: 0.2,
  // Two slumps cut into the year, because twelve months of unbroken practice
  // looks synthetic.
  slumps: [{ from: 250, to: 232 }, { from: 128, to: 111 }],
  rewardAgeDays: [300, 70, 40, 20]
};

/**
 * Fills the profile with a year of plausible practice. Overwrites the activity
 * log, walk history, rewards and theme goals — photos, rooms and custom themes
 * are left alone.
 */
export function seedDemoData(options = {}) {
  const cfg = { ...DEFAULTS, ...options };

  stashRealState();
  const summary = applyBackstory(cfg);
  state.demoMode = { seed: cfg.seed, seededAt: Date.now() };

  if (!save()) console.warn('PhotoWalk: demo data could not be written to storage — it will not survive a refresh.');
  window.dispatchEvent(new CustomEvent('photowalk:stats-changed'));

  console.info('PhotoWalk demo data seeded', summary);
  return summary;
}

/** Parks the user's real profile before the first seed overwrites it. */
function stashRealState() {
  if (localStorage.getItem(PRE_DEMO_KEY) !== null) return; // already parked
  try {
    localStorage.setItem(PRE_DEMO_KEY, localStorage.getItem(STATE_KEY) || '');
  } catch (err) {
    console.warn('PhotoWalk: could not park the real profile before seeding demo data.', err);
  }
}

/** Drops ?demo from the address bar without reloading, so a refresh is a clean one. */
function stripDemoParam() {
  const url = new URL(window.location.href);
  if (!url.searchParams.has('demo')) return;
  url.searchParams.delete('demo');
  window.history.replaceState({}, '', url.toString());
}

function wipeStats() {
  state.activityLog = {};
  state.frameLog = {};
  state.walkHistory = [];
  state.rewards = [];
  state.lastWalk = null;
  state.demoMode = null;
  Object.assign(state.profile, {
    streak: 0,
    longestStreak: 0,
    lastWalkDate: null,
    walksCompleted: 0,
    photosAnalyzed: 0,
    themeGoals: [],
    milestonesSeen: []
  });
  save();
  window.dispatchEvent(new CustomEvent('photowalk:stats-changed'));
}

/**
 * Leaves demo mode. Whatever profile was parked at the first seed is handed
 * back — which means a page reload, because the live state object was built
 * from the demo blob. With nothing parked, the stats are simply wiped.
 */
export function clearDemoData() {
  const parked = localStorage.getItem(PRE_DEMO_KEY);
  localStorage.removeItem(PRE_DEMO_KEY);
  stripDemoParam();

  if (parked === null) { wipeStats(); return false; }

  if (parked) localStorage.setItem(STATE_KEY, parked);
  else localStorage.removeItem(STATE_KEY);
  window.location.reload();
  return true;
}

/** True once the fixture has been seeded, until it is cleared. */
export function demoModeActive() {
  return Boolean(state.demoMode);
}

/**
 * Seeds only when there is something to fix: no demo data yet, a different seed
 * asked for, or a log that no longer reaches today. Boot calls this on every
 * load while demo mode is on, so a refresh keeps the screenshot intact and
 * opening the app tomorrow still shows a streak ending today.
 */
export function ensureDemoData(options = {}) {
  const seed = options.seed ?? (state.demoMode && state.demoMode.seed) ?? DEFAULTS.seed;
  const upToDate = state.demoMode
    && state.demoMode.seed === seed
    && state.walkHistory.length > 0
    && (state.activityLog[localDateKey()] || 0) > 0
    // A fixture seeded before the frame log existed has to be topped up too.
    && Object.keys(state.frameLog || {}).length > 0;
  if (upToDate) return null;
  return seedDemoData({ ...options, seed });
}

/**
 * Console handle: photowalkDemo.seed({ seed: 7 }) reseeds, .clear() restores the
 * real profile, .status() reports what the fixture currently claims.
 */
export function installDemoHooks() {
  window.photowalkDemo = {
    seed: seedDemoData,
    ensure: ensureDemoData,
    clear: clearDemoData,
    active: demoModeActive,
    status: () => ({
      ...(state.demoMode || { seed: null }),
      activeDays: Object.keys(state.activityLog).length,
      streak: state.profile.streak,
      totalHours: formatHours(totalActivityHours())
    })
  };
}
